package UI.Model;

public enum Permission {

    //CAN DO ALL
    FOUNDER,

    //CAN DO ALL EXCEPT FOUNDER STAFF (OWNER PERMISSION)
    OWNER,

    //PRODUCTS MANAGEMENT
    ADD_PRODUCT,
    CHANGE_PRODUCT_POLICY,
    CHANGE_SHOP_POLICY,

    //APPOINT MANAGEMENT
    APPOINT_MANAGER,
    REMOVE_OWNER, 
    REMOVE_MANAGER, 

    //PERMISSION MANAGEMENT
    CHANGE_PERMISSION, 

    //GENERAL
    GET_ROLES_INFO, 
    GET_CLIENT_REQUEST, 
    RESPONSE_TO_CLIENT_REQUEST, 
    GET_PURCHASE_HISTORY, 
}