package UI.Model;

public enum Permission {

    //CAN DO ALL
    FOUNDER,

    //CAN DO ALL EXCEPT FOUNDER STAFF (OWNER PERMISSION)
    OWNER,

    //PRODUCTS MANAGEMENT
    ADD_PRODUCT,
    DELETE_PRODUCT,
    PUBLISH_PRODUCT_FOR_SALE,
    REMOVE_PRODUCT_FROM_SALE,
    EDIT_PRODUCT,

    //POLICY MANAGEMENT (NOT FOR THIS VERSION)
    CHANGE_PURCHASE_POLICY,
    CHANGE_DISCOUNT_POLICY,
    ADD_PURCHASE_METHOD,
    REMOVE_PURCHASE_METHOD,
    ADD_DISCOUNT_POLICY,
    REMOVE_DISCOUNT_METHOD, 
    CHANGE_PRODUCT_POLICY,
    CHANGE_SHOP_POLICY,

    //APPOINT MANAGEMENT
    APPOINT_MANAGER,
    REMOVE_OWNER, 
    REMOVE_MANAGER, 

    //PERMISSION MANAGEMENT
    CHANGE_PERMISSION, 

    //GENERAL
    GET_ROLES_INFO, 
    GET_CLIENT_REQUEST, 
    RESPONSE_TO_CLIENT_REQUEST, 
    GET_PURCHASE_HISTORY, 
}